apiVersion: kustomize.config.k8s.io/v1beta
kind: Kustomization
namespace: argocd
resources:
- https://github.com/argoproj/argo-cd/raw/v2.14.21//manifests/install.yaml
- https://app.getambassador.io/yaml/emissary/3.9.1/emissary-crds.yaml
- resources.yaml
